### PR TITLE
Feature/test

### LINKED ISSUE #85: Add integration testing for `ProfileForm`
As a developer,

When I make a new component,

I want to have integration testing for it,

 So that I know my app works as I expect.

### PR DESCRIPTION
**Pull request by CalebCyphers**
## What's this PR do?
 - Adds Cypress to project
 - Adds Tests for User Profile Stories
 - Adds tests for ProfileForm profile editing stories

## Relevant tickets
- Closes #85 

## Where should the reviewer start?
- web > cypress > integration 

## How should this be manually tested?
- After pulling, run `npm install`
- use `npx cypress open` and click on App.spec.js

## Screenshots/GIFs
Screen Shot 2021-02-13 at 4 14 16 PM

### CODE REVIEW

**Comment by GarrettCottrell** [comment]
Looks good, Caleb!

**Review by the-color-bliu — APPROVED** [review]
Coming from a BEnder, these tests are very thorough and well commented, great job!

**Review by kncaputo — APPROVED** [review]

**Review by saraho1123 — APPROVED** [review]
Great job on the tests Caleb!

**Review by jdcarey128 — APPROVED** [review]
LGTM

**Pull request merged**
